name: Sequelize Boilerplate CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Connect to PostgreSQL and Create
        run: node client.js
        env:
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      - name: run unit tests
        run: npm run test-coverage
        env:
          CI: true
          NODE_ENV: 'test'
          DB_NAME: 'SequelizeBoilerplate'
          DB_USER: 'postgres'
          DB_PASS: 12345
          DB_HOST: 'localhost'
          TEST_DB_NAME: 'SequelizeBoilerplateTest'
          TEST_DB_USER: 'postgres'
          TEST_DB_PASS: 12345
          TEST_DB_HOST: 'localhost'
